# prefix
unbind C-b
set -g prefix C-o
bind C-o send-prefix

set -sg escape-time 0
set -g repeat-time 1000 ## prefix後のキー入力の受付時間 (ms)

# basic
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set -g focus-events on
set -g history-limit 20000

# window
## 作成
bind c new-window -c '#{pane_current_path}'

## 分割
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'

## 移動
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# pane
## 移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r o select-pane -t :.+
bind -r O select-pane -t :.-

## resize
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

## border
set -g pane-border-status top
set -g pane-border-format " #{pane_index} #{pane_current_command} #{b:pane_current_path} "
set -g pane-active-border-style fg=green
set -g pane-border-style fg=colour238
set -g pane-border-lines simple


# status bar
set -g status-interval 5
set -g status-left  "#S "
set -g status-right "%Y-%m-%d %H:%M "
set -g window-status-format " #I:#W "
set -g window-status-current-format " [#I:#W] "

# copy mode
set -g mode-keys emacs
set -g set-clipboard on

# reload
bind r source-file ~/.tmux.conf \; display-message "Reloaded ~/.tmux.conf"

# Plugins (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
